from tkinter import *
from math import pi
import for_figure_7 as f7
root = Tk()
# root.resizable(width=False, height=False)
root.title('Калькулятор площади/объема')

def result_Sb():
    P = float(entry.get())
    h = float(entry2.get())
    air.destroy()
    Po.destroy()
    H.destroy()
    entry.destroy()
    entry2.destroy()
    result_button.destroy()
    result = Label(root, text=P * h)
    result.pack()

def result_Sn():
    So = float(entry.get())
    S2o = So * 2
    Sb2 = float(entry2.get())
    air.destroy()
    Sb.destroy()
    So2.destroy()
    entry.destroy()
    entry2.destroy()
    result_button.destroy()
    result = Label(root, text=S2o + Sb2)
    result.pack()

def result_V():
    So2 = float(entry.get())
    h = float(entry2.get())
    air.destroy()
    H.destroy()
    So1.destroy()
    entry.destroy()
    entry2.destroy()
    result_button.destroy()
    result = Label(root, text=So2 * h)
    result.pack()

def result_So():
    A = float(entry.get())
    H = float(entry2.get())
    air.destroy()
    a.destroy()
    h.destroy()
    entry.destroy()
    entry2.destroy()
    result_button.destroy()
    result = Label(root, text=A * H / 2)
    result.pack()

def formula_Sb():
    global air, Po, H, entry, entry2, result_button
    choice.destroy()
    Sn.destroy()
    Sb.destroy()
    V.destroy()
    So.destroy()
    formula = Label(root, text='Sб = Po ∙ H')
    air = Label(root, text='')
    Po = Label(root, text='Po = ')
    H = Label(root, text='H = ')
    entry = Entry(root, width=12)
    entry2 = Entry(root, width=12)
    result_button = Button(root, text='Result', command=result_Sb)
    formula.pack()
    air.pack()
    Po.pack()
    entry.pack()
    H.pack()
    entry2.pack()
    result_button.pack()

def formula_Sn():
    global air, So2, Sb, entry, entry2, result_button
    choice.destroy()
    Sn.destroy()
    Sb.destroy()
    V.destroy()
    So.destroy()
    formula = Label(root, text='Sn = 2So + Sб')
    air = Label(root)
    So2 = Label(root, text='So = ')
    Sb = Label(root, text='Sб = ')
    entry = Entry(root, width=12)
    entry2 = Entry(root, width=12)
    result_button = Button(root, text='Result', command=result_Sn)
    formula.pack()
    air.pack()
    So2.pack()
    entry.pack()
    Sb.pack()
    entry2.pack()
    result_button.pack()

def formula_V():
    global air, So1, H, entry, entry2, result_button
    choice.destroy()
    Sn.destroy()
    Sb.destroy()
    V.destroy()
    So.destroy()
    formula = Label(root, text='V = So ∙ H')
    air = Label(root)
    So1 = Label(root, text='So = ')
    H = Label(root, text='H = ')
    entry = Entry(root, width=12)
    entry2 = Entry(root, width=12)
    result_button = Button(root, text='Result', command=result_V)
    formula.pack()
    air.pack()
    So1.pack()
    entry.pack()
    H.pack()
    entry2.pack()
    result_button.pack()
def formula_So():
    global air, a, h, entry, entry2, result_button
    choice.destroy()
    Sn.destroy()
    Sb.destroy()
    V.destroy()
    So.destroy()
    formula = Label(root, text='So = ah/2')
    air = Label(root)
    a = Label(root, text='a = ')
    h = Label(root, text='h = ')
    entry = Entry(root, width=12)
    entry2 = Entry(root, width=12)
    result_button = Button(root, text='Result', command=result_So)
    formula.pack()
    air.pack()
    a.pack()
    entry.pack()
    h.pack()
    entry2.pack()
    result_button.pack()

def result52():
    a = float(entry_512.get())
    h = float(entry_522.get())
    entry_512.destroy()
    entry_522.destroy()
    air5.destroy()
    a5.destroy()
    h5.destroy()
    result_button52.destroy()
    result = Label(root, text=a*h)
    result.pack()
def result5():
    d11 = float(entry_51.get())
    d21 = float(entry_52.get())
    air5.destroy()
    d1.destroy()
    d2.destroy()
    entry_51.destroy()
    entry_52.destroy()
    result_button5.destroy()
    result = Label(root, text=d11*d21/2)
    result.pack()
def formula1():
    global air5, d1, d2, entry_51, entry_52, result_button5
    title2.destroy()
    button.destroy()
    button2.destroy()
    formula = Label(root, text='S = d₁d₂/2')
    air5 = Label(root, text="")
    d1 = Label(root, text='d₁ = ')
    d2 = Label(root, text='d₂ = ')
    entry_51 = Entry(root, width=12)
    entry_52 = Entry(root, width=12)
    result_button5 = Button(root, height=1, width=12, text='Result', command=result5)
    formula.pack()
    air5.pack()
    d1.pack()
    entry_51.pack()
    d2.pack()
    entry_52.pack()
    result_button5.pack()

def formula2():
    global air5, a5, h5, entry_512, entry_522, result_button52
    title2.destroy()
    button.destroy()
    button2.destroy()
    formula = Label(root, text='S = ah')
    air5 = Label(root, text='')
    a5 = Label(root, text='a = ')
    h5 = Label(root, text='h = ')
    entry_512 = Entry(root, width=12)
    entry_522 = Entry(root, width=12)
    result_button52 = Button(root, width=12, text='Result', command=result52)
    formula.pack()
    air5.pack()
    a5.pack()
    entry_512.pack()
    h5.pack()
    entry_522.pack()
    result_button52.pack()
def result():
    a = float(entry_1.get())
    b = float(entry_2.get())
    result = Label(root, text=a*b)
    air.destroy()
    a1.destroy()
    entry_1.destroy()
    b1.destroy()
    entry_2.destroy()
    result_button.destroy()
    result.pack()

def result2():
    a = float(entry_21.get())
    h = float(entry_22.get())
    result = Label(root, text=a * h/2)
    air2.destroy()
    a2.destroy()
    entry_21.destroy()
    h2.destroy()
    entry_22.destroy()
    result_button2.destroy()
    result.pack()

def result3():
    r = float(entry_3.get())
    r2 = r**2
    result = Label(root, text=r2*pi)
    air3.destroy()
    r3.destroy()
    entry_3.destroy()
    result_button3.destroy()
    result.pack()

def result4():
    a = float(entry_41.get())
    b = float(entry_42.get())
    c = float(entry_43.get())
    result = Label(root, text=a * b * c)
    air4.destroy()
    a4.destroy()
    b4.destroy()
    c4.destroy()
    entry_41.destroy()
    entry_42.destroy()
    entry_43.destroy()
    result_button4.destroy()
    result.pack()

def result6():
    a1 = float(entry_61.get())
    h1 = float(entry_62.get())
    a.destroy()
    h.destroy()
    entry_61.destroy()
    entry_62.destroy()
    air6.destroy()
    result_button.destroy()
    result = Label(root, text=a1*h1)
    result.pack()

def fun_figure_1():
    global entry_1, entry_2, air, result_button, a1, b1
    title.destroy()
    figure_1.destroy()
    figure_2.destroy()
    figure_3.destroy()
    figure_4.destroy()
    figure_5.destroy()
    figure_6.destroy()
    figure_7.destroy()
    formula = Label(root, text='S = ab')
    air = Label(root, text=' ')
    a1 = Label(root, text='a = ')
    b1 = Label(root, text='b = ')
    entry_11 = Entry(root, width=12)
    entry_12 = Entry(root, width=12)
    result_button = Button(root, text='Result', command=result)
    formula.pack()
    air.pack()
    a1.pack()
    entry_11.pack()
    b1.pack()
    entry_12.pack()
    result_button.pack()

def fun_figure_2():
    global entry_21, entry_22, h2, a2, air2, result_button2
    title.destroy()
    figure_1.destroy()
    figure_2.destroy()
    figure_3.destroy()
    figure_4.destroy()
    figure_5.destroy()
    figure_6.destroy()
    figure_7.destroy()
    formula = Label(root, text='S = ah/2')
    a2 = Label(root, text='a = ')
    air2 = Label(root, text='')
    entry_21 = Entry(root, width=12)
    entry_22 = Entry(root, width=12)
    h2 = Label(root, text='h = ')
    result_button2 = Button(root, text='Result', command=result2)
    formula.pack()
    air2.pack()
    a2.pack()
    entry_21.pack()
    h2.pack()
    entry_22.pack()
    result_button2.pack()
def fun_figure_3():
    global air3, r3, entry_3, result_button3
    title.destroy()
    figure_1.destroy()
    figure_2.destroy()
    figure_3.destroy()
    figure_4.destroy()
    figure_5.destroy()
    figure_6.destroy()
    figure_7.destroy()
    formula = Label(root, text='S = r² ∙ pi')
    air3 = Label(root, text="")
    r3 = Label(root, text='r = ')
    entry_3 = Entry(root, width=12)
    result_button3 = Button(root, text='Result', command=result3)
    formula.pack()
    air3.pack()
    r3.pack()
    entry_3.pack()
    result_button3.pack()

def fun_figure_4():
    global air4, a4, b4, c4, entry_41, entry_42, entry_43, result_button4
    title.destroy()
    figure_1.destroy()
    figure_2.destroy()
    figure_3.destroy()
    figure_4.destroy()
    figure_5.destroy()
    figure_6.destroy()
    figure_7.destroy()
    formula = Label(root, text='V = abc')
    air4 = Label(root, text="")
    a4 = Label(root, text='a = ')
    b4 = Label(root, text='b = ')
    c4 = Label(root, text='c = ')
    entry_41 = Entry(root, width=12)
    entry_42 = Entry(root, width=12)
    entry_43 = Entry(root, width=12)
    result_button4 = Button(root, text='Result', command=result4)
    formula.pack()
    air4.pack()
    a4.pack()
    entry_41.pack()
    b4.pack()
    entry_42.pack()
    c4.pack()
    entry_43.pack()
    result_button4.pack()
def fun_figure_5():
    global title2, button, button2
    title.destroy()
    figure_1.destroy()
    figure_2.destroy()
    figure_3.destroy()
    figure_4.destroy()
    figure_5.destroy()
    figure_6.destroy()
    figure_7.destroy()
    title2 = Label(root, text='Выбери формулу')
    button = Button(root, text='S = d₁d₂/2', command=formula1)
    button2 = Button(root, text='S = ah', command=formula2)
    title2.grid(row=0, column=1)
    button.grid(row=1, column=0)
    button2.grid(row=1, column=2)

def fun_figure_6():
    global air6, a, h, entry_61, entry_62, result_button
    title.destroy()
    figure_1.destroy()
    figure_2.destroy()
    figure_3.destroy()
    figure_4.destroy()
    figure_5.destroy()
    figure_6.destroy()
    figure_7.destroy()
    formula = Label(root, text='S = ah')
    air6 = Label(root, text='')
    a = Label(root, text='a = ')
    h = Label(root, text='h = ')
    entry_61 = Entry(root, width=12)
    entry_62 = Entry(root, width=12)
    result_button = Button(root, text='Result', command=result6)
    formula.pack()
    air6.pack()
    a.pack()
    entry_61.pack()
    h.pack()
    entry_62.pack()
    result_button.pack()

def fun_figure_7():
    global choice, So, Sb, Sn, V
    title.destroy()
    figure_1.destroy()
    figure_2.destroy()
    figure_3.destroy()
    figure_4.destroy()
    figure_5.destroy()
    figure_6.destroy()
    figure_7.destroy()
    choice = Label(root, text='Выбери формулу')
    So = Button(root, text='So = ah/2', command=formula_So)
    Sn = Button(root, text='Sn = 2So + Sб', command=formula_Sn)
    V = Button(root, text='V = So ∙ H', command=formula_V)
    Sb = Button(root, text='Sб = Po ∙ H', command=formula_Sb)
    choice.grid(row=0, column=1)
    So.grid(row=1, column=0)
    Sb.grid(row=2, column=0)
    V.grid(row=1, column=2)
    Sn.grid(row=2, column=2)



title = Label(root, text='Выбери фигуру')
figure_1 = Button(root, text='Прямоугольник', command=fun_figure_1)
figure_2 = Button(root, text='Треугольник', command=fun_figure_2)
figure_3 = Button(root, text='Круг', command=fun_figure_3)
figure_4 = Button(root, text='Куб', command=fun_figure_4)
figure_5 = Button(root, text='Ромб', command=fun_figure_5)
figure_6 = Button(root, text='Параллелограмм', command=fun_figure_6)
figure_7 = Button(root, text="Прямая треугольная призма", command=fun_figure_7)

title.pack()
figure_7.pack()
figure_6.pack()
figure_1.pack()
figure_2.pack()
figure_3.pack()
figure_5.pack()
figure_4.pack()



root.mainloop()